#index:
#    path: /
#    controller: App\Controller\DefaultController::index
logout:
    path: /logout
hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /demo/secured/connect

facebook_login:
    path: /demo/secured/login_facebook
